name: Build .Net Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BASE_PATH: . # The base path for the project files
  VERSION_MAJOR: 1 # The major version
  VERSION_MINOR: 0 # The minor version
  DOCKER_FILE: Dockerfile # The docker file name
  CONTAINER_REGISTRY: thomiles.azurecr.io # The docker image registry

jobs:
  build-dotnet:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push
      env:
        DOCKER_TAG: "${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.${{ env.GITHUB_RUN_NUMBER }}"
        DOCKER_IMAGE: "${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}" # The image to build
      run: |
        docker pull $DOCKER_IMAGE:latest || true
        docker build --cache-from $DOCKER_IMAGE:latest --tag $DOCKER_IMAGE:$DOCKER_TAG --tag $DOCKER_IMAGE:latest -f $DOCKER_FILE ./$BASE_PATH
        docker push $DOCKER_IMAGE:$DOCKER_TAG
        docker push $DOCKER_IMAGE:latest
